//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustom
    {
        public int Custom_ID { get; set; }
        public string ct_01 { get; set; }
        public string ct_02 { get; set; }
        public string ct_03 { get; set; }
        public string ct_04 { get; set; }
        public string ct_05 { get; set; }
        public string ct_06 { get; set; }
        public string ct_07 { get; set; }
    }
}
