//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPostLang
    {
        public int Post_ID { get; set; }
        public int Lang_ID { get; set; }
        public Nullable<System.DateTime> PostLang_DateAdd { get; set; }
    
        public virtual tblLanguage tblLanguage { get; set; }
        public virtual tblPost tblPost { get; set; }
    }
}
