//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTag
    {
        public int Tag_ID { get; set; }
        public string Tag_Title { get; set; }
        public Nullable<int> Tag_CountSearch { get; set; }
        public Nullable<System.DateTime> Tag_DateAdd { get; set; }
    }
}
