//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShareCode.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblUser()
        {
            this.tblComments = new HashSet<tblComment>();
            this.tblPosts = new HashSet<tblPost>();
            this.tblRepplies = new HashSet<tblRepply>();
        }
    
        public int User_ID { get; set; }
        public string User_DisplayName { get; set; }
        public string User_Password { get; set; }
        public Nullable<System.DateTime> User_DateLogin { get; set; }
        public Nullable<bool> User_Active { get; set; }
        public Nullable<bool> User_Trash { get; set; }
        public string User_Token { get; set; }
        public Nullable<int> User_Role { get; set; }
        public string User_Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblComment> tblComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPost> tblPosts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRepply> tblRepplies { get; set; }
        public virtual tblRole tblRole { get; set; }
    }
}
